### ISSUE TITLE
Why the TM-score and GDT-TS for T1043 in CASP14 are so low

### ISSUE THREAD

**Issue by wuwo007** [deepmind/alphafold#111]
When I used the trained models ('model_1','model_2''model_3','model_4''model_5') to predict the structure of proteins of CASP14, I found that some proteins' TM-score and GDT-TS are very low. For example, the TM-score and GDT-TS for T1043 are as follows:
TM-score    = 0.2122  (d0= 4.53)
MaxSub-score= 0.1278  (d0= 3.50)
GDT-TS-score= 0.1875 %(d<1)=0.1149 %(d<2)=0.1284 %(d<4)=0.1622 %(d<8)=0.3446
GDT-HA-score= 0.1284 %(d<0.5)=0.1081 %(d<1)=0.1149 %(d<2)=0.1284 %(d<4)=0.1622
The CASP14 protein sequence and the target protein structure are download from here :https://www.predictioncenter.org/download_area/CASP14/ 
The TM-score and GDT-score are calculated by the tool shared by zhanglab (https://zhanglab.ccmb.med.umich.edu/TM-score/). 
Does anyone knows why the TM-score and GDT-TS for T1043 in CASP14 are so low?

**Comment by yamule** [comment]
T1043 is only a portion of T1044. As it's not a complete protein, interactions with other regions might be needed to fold.
What happen if you use T1044 seq to predict the complete protein and extract the region corresponds to T1043?
I recommend TMalign because re-assigning sequence number is tiresome.
