### ISSUE TITLE
Problem in using Alphafold2 code in Colab PRO

### ISSUE THREAD

**Issue by pchatterjee-cmd** [deepmind/alphafold#157]
Dear Experts,

I am trying to run Alphafold2 job in Colab PRO, but it is failing repeatedly (accessed from my google account prathit.biophysics@gmail.com).

My sequence is the 770 residue variant APP (Amyloid-beta-precursor protein) already modeled with Alphafold2 (https://www.alphafold.ebi.ac.uk/entry/P05067), for making homoligomer (dimer, for now).

I am attaching the error message along with.
<img width="1329" alt="Screen Shot 2021-09-01 at 5 33 15 PM" src="https://user-images.githubusercontent.com/84581049/131645642-897dea7d-23a8-4fa9-b1fa-574770eb849d.png">

Any suggestions will be deeply appreciated.

Thank you in advance,
Sincerely,
Prathit Chatterjee

**Comment by pchatterjee-cmd** [comment]
Dear Experts,

I tried further by omitting the first ~ 25 residues and reducing the num_models to  only 1, after switching to high power RAM.
In spite of that, the job failed.

I am sending you the corresponding snapshots.
<img width="1635" alt="Screen Shot 2021-09-01 at 8 41 36 PM" src="https://user-images.githubusercontent.com/84581049/131665660-3ad4bced-418c-44cb-805e-3198abfbfd78.png">
<img width="1637" alt="Screen Shot 2021-09-01 at 8 41 04 PM" src="https://user-images.githubusercontent.com/84581049/131665683-dfa16fc4-36db-488b-a7ed-5f93f3161c7c.png">

**Comment by gkovacs-research** [comment]
Hello,

I think, you are using ColabFold's notebook based on the cf.to() function call in your stack trace. Their Colab notebook imports their code with that alias:

`import colabfold as cf`

Most likely your issue belongs to that GitHub repo's issue tracker:

https://github.com/sokrypton/ColabFold

It seems that RAM / VRAM requirements grow w.r.t the amino acid sequence length you provide, and that's why you run into an OOM error. I've run a prediction for you using Deepmind's notebook. With those 5 models I could fit in the Colab Pro memory limits. I send the results attached, maybe you'll find them useful:

[predictions_APP.zip](https://github.com/deepmind/alphafold/files/7091734/predictions_APP.zip)

**Comment by pchatterjee-cmd** [comment]
Dear Dr. Kovacs,

Thank you very much for your response.
Nevertheless, I mention here that the prediction of monomeric structure was
possible even in my case.

However, while trying to predict homooligomerization (starting with
homodimers at first), the OOM error occurred.

Sincerely,
Prathit

**Comment by pchatterjee-cmd** [comment]
Additional information:

Even after reducing the total residue number from 770 to finally 665, the Out of Memory problem occurs in the step "GATHER INPUT FEATURES, PREDICT STRUCTURES".
