### ISSUE TITLE
Error while running singularity with --preset=reduced_dbs flag 

### ISSUE THREAD

**Issue by marekb-sci** [deepmind/alphafold#176]
After running singularity container with `--preset=reduced_dbs` flag I got 
```
/opt/alphafoldenv/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
FATAL Flags parsing error: flag --preset=reduced_dbs: value should be one of <full_dbs|casp14>
Pass --helpshort or --helpfull to see help on flags.
```

**Comment by Augustin-Zidek** [comment]
Hi Marek,

This is most likely because the Singularity Container hasn't been updated to be in sync with the repository (we don't officially support the Singularity Container). It therefore doesn't reflect the changes we added in https://github.com/deepmind/alphafold/commit/0bab1bf84d9d887aba5cfb6d09af1e8c3ecbc408 – this is where we added the `reduced_dbs` preset.
