### ISSUE TITLE
Use custom templates in alphafold2

### ISSUE THREAD

**Issue by JMacnar** [deepmind/alphafold#190]
Dear AlphaFold authors,

I am writing to you to ask if it would be possible for us to use a partially solved structure as an input to your AlphaFold2 docker implementation.
I would be grateful for your suggestions on how to proceed to incorporate other templates that are not yet in PDB. As far as I understand AF2 first is looking to the sequence databases and then is searching PDB70 to finally checks mmcifs. Would it be a good idea to add our structure to the directory where all mmcifs are stored and also somehow include it in the pdb70?

Regards,
JMacnar

**Comment by abridgland** [comment]
Hi Joanna, I'm afaid there isn't a simple solution here and I'll also mention that even if you add a template, there's no guarantee about how much it will affect the model's output. If you do want to add a template manually you could try adding the mmCIF alongside the others in the pdb_mmcif directory and then I'd recommend adding the template's name and sequence to pdb_seqres.txt and use hmmsearch (hhsearch uses pdb70 which will be harder to modify manually). You'll also probably have to set the `max_subsequence_ratio` [here](https://github.com/deepmind/alphafold/blob/db039ef4230081808aff4d3fcf8eb83c52348004/alphafold/data/templates.py#L179) to a value over `1.0` to prevent it being ignored if there's too much of a sequence overlap. If for some reason the third party template search tools aren't picking up the template after that then your best bet is to manually build an instance of `parsers.TemplateHit` in the `DataPipeline.process` function and insert it at the start of the `pdb_template_hits` list that's created [here](https://github.com/deepmind/alphafold/blob/db039ef4230081808aff4d3fcf8eb83c52348004/alphafold/data/pipeline.py#L194). Once again, you'll need the template mmcif in the usual mmcif directory and you'll need to ensure it's not removed due to high sequence overlap.

Apologies that there's not a simpler solution at the moment! I'll make a note that this is something that we might want to simplify in future releases.

**Comment by jkosinski** [comment]
Dear Alex,

A side question to max_subsequence_ratio - we have noticed max_subsequence_ratio before and found that we need to change it to 1.0 when we want to include templates that have the subsequence identical to the query. Do you know the reasoning behind setting it to 0.95 by default? When is it useful? Obviously, if the structure is known for 95% of the sequence, there is not much need to run AlphaFold. Still, in many, if not most, real applications, users do not want to ignore such templates (e.g., in high-throughput modeling runs where some of the sequences have structures known, when users want to complete the remaining 5%, or when using hhsearch for template search for multimers in modified protocols like in ColabFold).

Best,
Jan

**Comment by abridgland** [comment]
Hi Jan,

Thanks for raising this point. The 95% filtering was using during training and inference for the extensive analysis done in the paper, the original reasoning being that you may be more likely to get different conformations when not providing 100% templates.  In practice it may well be better to provide these 100% templates, but we would have to repeat the large scale analysis to confirm this is the case before making it the default. Unfortunately this isn't part of our plans for future updates. 

Best,
Alex

**Comment by aravinda1879** [comment]
Hi,
Is there a way to specify hmmsearch for template searching in monomer version? I see that hmmsearch only works within multimer? 
Thanks!
