### ISSUE TITLE
Cannot create a tensor proto whose content is larger than 2GB.

### ISSUE THREAD

**Issue by HimansuKumarIIITA** [deepmind/alphafold#234]
Hi ,

When I am running for smaller amino acids sequences protein, the tool is running perfectly fine. When we use longer amino acids protein such as more than 1000 amino acids protein. Its showing error such as :

I1030 14:11:24.108233 140521650726720 run_docker.py:195] "Cannot create a tensor proto whose content is larger than 2GB.")
I1030 14:11:24.108459 140521650726720 run_docker.py:195] ValueError: Cannot create a tensor proto whose content is larger than 2GB.

As I am searching on internet for this issue, some one has mentioned about tensor flow version may be the reason.

I also  wanted to know that, is alpha fold is equally efficient in case of fusion protein such as bcr-abl also?

Thank you

**Comment by Augustin-Zidek** [comment]
Hi, which AlphaFold version are you running with? Are you running with v2.0.0 or v2.1.0+?

**Comment by HimansuKumarIIITA** [comment]
I am using AlphaFold v2.0.

As it has been mentioned in read me file.

![header](imgs/header.jpg)
# AlphaFold

This package provides an implementation of the inference pipeline of AlphaFold
v2.0. This is a completely new model that was entered in CASP14 and published in
Nature. For simplicity, we refer to this model as AlphaFold throughout the rest
of this document.

**Comment by Augustin-Zidek** [comment]
This is the overall version (I need to update the README to make this clearer, sorry!), however, we had a few releases since and we are currently on version v2.1.1 (see https://github.com/deepmind/alphafold/releases).

We fixed the issue you are seeing in v2.1.0. Did you install AlphaFold before November 2nd? If so, then you are definitely running the older version (v2.0.0 or v2.0.1) and I recommend upgrading. Alternatively, if you don't want to upgrade, you can use the fix suggested here: https://github.com/deepmind/alphafold/pull/216.

**Comment by HimansuKumarIIITA** [comment]
Thanks for your reply.
Do I need to downlead the database again, or just upgrade the alphafold tool and give the path of already downloaded database?

**Comment by Augustin-Zidek** [comment]
If you want to keep using only the monomer system, you can reuse the databases you have and just pass this path to the run script.

There is a more extensive documentation at https://github.com/deepmind/alphafold#updating-existing-alphafold-installation-to-include-alphafold-multimers.
