### ISSUE TITLE
Custom genetic database

### ISSUE THREAD

**Issue by ihbxiongjie** [deepmind/alphafold#244]
Hi, all

Is it possible to include the custom genetic database when run AF2?

Best,

Jie

**Comment by Augustin-Zidek** [comment]
It is possible, but only with a code change in `data/pipeline.py`: 
* If the database is a FASTA file, you could add a new Jackhmmer searcher for that database. You can take a look at the `jackhmmer_uniref90_runner` and basically follow the same logic for your database.
* If the database is a HH Suite database, you could add a new HHBlits searcher for that database. You can take a look at the `hhblits_bfd_uniclust_runner` for inspiration in this case.

Alternatively, if this is a custom FASTA file, you could try passing that instead of one of the existing databases, e.g. small_BFD or MGnify. Note this might lead to worse results as you would be replacing one database with another.
