### ISSUE TITLE
Use updated uniclust database

### ISSUE THREAD

**Issue by ihbxiongjie** [deepmind/alphafold#257]
There is an updated uniclust database "UniRef30_2021_06_hhsuite.tar.gz", is it OK to instead it as the 2018 version?

**Comment by Shall-We-Dance** [comment]
Yes, I've tried to update the uniclust database, and it works.

One of my collaborator gave me a sequence that will meet `"HHblits fail"` on 2018 version, this problem is solved when using 2020 version.

BTW, you need to change the `run_docker.py` at the sametime.

- download [2020_06 version](http://gwdu111.gwdg.de/~compbiol/uniclust/2020_06/UniRef30_2020_06_hhsuite.tar.gz) to  `<DOWNLOAD_DIR>/uniclust30`.

- Tar it as a folder named `uniclust30_2020_06`, then vim the `./docker/run_ducker.py` in line 122

   from

  `FLAGS.data_dir, 'uniclust30', 'uniclust30_2018_08', 'uniclust30_2018_08’)`

  to

   ` FLAGS.data_dir, 'uniclust30', 'uniclust30_2020_06', 'UniRef30_2020_06')`

You can use 2021 version as well.

**Comment by Augustin-Zidek** [comment]
Yes, it is absolutely OK to use a more recent version of any of the databases. The instructions from @Shall-We-Dance are great.
