### ISSUE TITLE
Upload own MSA

### ISSUE THREAD

**Issue by MajekNovotny** [deepmind/alphafold#300]
Would it be possibly to provide own MSA file for Alphafold instead of running HHblitz, please?

**Comment by abridgland** [comment]
Hi, we don't have short-term plans to add support for custom MSAs since this codebase aims to provide a reference implementation of the AF2 paper, and the MSA search is a required part of the validated system.

However if you do want to run a custom MSA you could either modify `DataPipeline.process` by removing the lines that run the MSA tools, and instead read your MSA file, parse it with one of the parsers in parsers.py and then give the result to `make_msa_features`, like we do for the usual MSAs.

Alternatively you can replace any of the MSA tool outputs with your custom MSA by creating a file with the appropriate filename in the MSA output directory (e.g. `bfd_uniclust_hits.a3m`) and running with `--use_precomputed_msas`. If you opt for this option then note that you'll also need to provide MSA files for the other MSAs, even if they're blank. Also note that they should be located in a directory called `msas` within the output directory specified when running using the `--output_dir` flag.
