### ISSUE TITLE
To resume runs killed by timeout

### ISSUE THREAD

**Issue by hittsuji** [deepmind/alphafold#313]
I'm running alfafold on limited resources. For prediction of a protein with ~3700 aa was killed by timeout (set 36 h walltime). I wonder if there are ways to resume the run using the files already generated.
Only I could find was using --use_precomputed_msas, but it's not clear how it is used.
I just found that adding --use_precomputed_msas=TRUE work if I use the same --output_dir as the killed run, but did not look to save a lot of time. (I could not try with long walltime because it consumes my allocated CPU/GPU time)
If any script to resume (or to split a run into multiple pieces) runs, please let me know. Sorry for the very novice question.
Thanks.

My code looks like:

export SINGULARITYENV_TF_FORCE_UNIFIED_MEMORY=1
export SINGULARITYENV_XLA_PYTHON_CLIENT_MEM_FRACTION=4.0

DOWNLOAD_DIR=/path/to/alphafold_2.1.1

singularity exec --nv /path/to/containers/alphafold_2.1.1.sif python /app/alphafold/run_alphafold.py  \
 --data_dir=$DOWNLOAD_DIR  \
 --uniref90_database_path=$DOWNLOAD_DIR/uniref90/uniref90.fasta  \
 --mgnify_database_path=$DOWNLOAD_DIR/mgnify/mgy_clusters_2018_12.fa  \
 --bfd_database_path=$DOWNLOAD_DIR/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt  \
 --uniclust30_database_path=$DOWNLOAD_DIR/uniclust30/uniclust30_2018_08/uniclust30_2018_08  \
 --pdb70_database_path=$DOWNLOAD_DIR/pdb70/pdb70  \
 --template_mmcif_dir=$DOWNLOAD_DIR/pdb_mmcif/mmcif_files  \
 --obsolete_pdbs_path=$DOWNLOAD_DIR/pdb_mmcif/obsolete.dat \
 --model_preset=monomer \
 --max_template_date=2021-12-1 \
 --db_preset=full_dbs \
 --output_dir=/path/to/result_out/ \
 --fasta_paths=/path/to/fasta

**Comment by Ni-Ar** [comment]
I also would like to know what is `--use_precomputed_msas=true` actually doing.

**Comment by Augustin-Zidek** [comment]
The `--use_precomputed_msas` flag does the following: If set to `true` AlphaFold first looks if there is already an MSA file for the given tool/database pair and if so, it will use that instead of running the MSA tool. If it can't find such file, it will run the MSA tool. Since the `output_directory` is used for this lookup, it indeed has to stay the same between the runs where you want to reuse the MSA files.

The MSA tools are usually not the bottleneck though, especially for long proteins and in your case it looks more likely that the protein you are trying too fold is too long. Unfortunately it is not possible to save checkpoints and resume while folding the protein.

I recommend either:
1. Waiting longer for it to fold, assuming you have a GPU with enough RAM to do it.
2. Split the sequence into multiple overlapping chunks (e.g. 1,500-residue chunks with 300-residue overlaps) and fold each separately, then reassemble the predicted structures into the full structure.

I hope this helps, feel free to reopen if not :)
