### ISSUE TITLE
Deploy Problem: Does AlphaFold2 working well at AMD 7002/7003 platform？

### ISSUE THREAD

**Issue by genomicsgroup** [deepmind/alphafold#318]
We are planning to purchase a GPU node to accelerate AlphaFold2 calculations, but we don’t know whether AMD7002/7003 series CPUs can support AlphaFold2 calculations. Can anyone provide advice, is it better to deploy AlphaFold2 with A100GPU and use AMD7002/7003 series CPU or use Intel Xeon Scalable 3 series instand?

**Comment by Augustin-Zidek** [comment]
AlphaFold should work well on Intel and AMD CPUs, especially since most of the compute-intensive tasks (i.e. the actual folding) happen on the GPU. The MSA search (Jackhmmer, HHBlits) and relaxation (OpenMM) which run currently on CPU and are CPU intensive should both work well on Intel and AMD CPUs.
