### ISSUE TITLE
"stereo_chemical_props.txt" missing for model relaxation

### ISSUE THREAD

**Issue by jhpanda** [deepmind/alphafold#32]
Hi Developers of AlphaFold2,

Thanks for sharing alphafold! It's really exciting!

I noticed that a file, `alphafold/common/stereo_chemical_props.txt`, containing structural parameters, is needed for model relaxation as indicated in `alphafold/common/residue_constants.py` line 406. But this file is actually missing in folder `alphafold/common`

Although it's not hard to find a similar file in openstructure (https://openstructure.org), I think adding this file to the folder would be great for others!

Best,
Junhui

**Comment by tfgg** [comment]
Hi Junhui,

This file should be copied over during the Docker build process as given in the Dockerfile:

https://github.com/deepmind/alphafold/blob/main/docker/Dockerfile#L60-L61

Is that not working?

(If you are setting up without using Docker I recommend following the Dockerfile to make sure you get all the steps and correct versions.)

**Comment by jhpanda** [comment]
Oh, I was running it on a non docker cluster using the script `run_alphafold.py`. Thanks for clarifying!

**Comment by tfgg** [comment]
No problem! I believe there are some other issues discussing how to run it without Docker, if that helps.

**Comment by vinicius-dev-app** [comment]
I had a similar problem on a non_docker install.

I noticed that the file failed to download due to a certificate error reported by wget. The command indicated on the [website](https://github.com/kalininalab/alphafold_non_docker) uses the `-q` option. This option prevented the error from being reported.

The command for "Download chemical properties to the common folder" is indicated on the website:
`wget -q -P alphafold/alphafold/common/ https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt`

I just removed the `-q` and used `--no-check-certificate`. This solved my case:
`wget --no-check-certificate -P alphafold/alphafold/common/ https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt`
