### ISSUE TITLE
How to generate features.pkl when using mmseqs2

### ISSUE THREAD

**Issue by YiningWang2** [deepmind/alphafold#341]
Hi, when i used mmseqs2 to generate MSA, i got six files by searching two databases: .a3m,.dbtype,.index. I noticed that making inference need features.pkl, do you know how to change files mentioned above into features.pkl?

**Comment by fereidoon27** [comment]
In AlphaFold, MSAs are built using jackhmmer and HHblits. To avoid the extensive data downloads and CPU processing, precomputed MSAs and the feature.pkl file can be used instead.

Due to my limited resources, I'm focusing on the GPU-based second step and considering tools like ColabFold to create the feature.pkl files.

What files and steps are needed to create the feature.pkl file? Is there a tool available on Google Colab or Kaggle for this?

**Comment by fereidoon27** [comment]
@YiningWang2 
In AlphaFold, MSAs are built using jackhmmer and HHblits. To avoid the extensive data downloads and CPU processing, precomputed MSAs and the feature.pkl file can be used instead.

Due to my limited resources, I'm focusing on the GPU-based second step and considering tools like ColabFold to create the feature.pkl files.

What files and steps are needed to create the feature.pkl file? Is there a tool available on Google Colab or Kaggle for this?
