### ISSUE TITLE
bfd and small bfd

### ISSUE THREAD

**Issue by liuxm117** [deepmind/alphafold#362]
Is the bfd database and the small_bfd database an inclusive relationship? Why is the same sequence, using bfd for msa, the generated file is smaller?

**Comment by Augustin-Zidek** [comment]
Hi,

small_bfd is a strict subset of BFD, generated by taking only the first non-consensus sequence from every cluster in BFD.

The reason the MSA files from BFD are smaller is probably because of a different format. We use HHBlits to search BFD which uses a3m as the output format. We use Jackhmmer to search small_bfd which uses sto (Stockholm) as the output format. Stockholm files are generally larger than a3m files even when the number of sequences is the same in both. 

If you mean smaller = less sequences, then this is probably due to the different algorithm used by HHBlits and Jackhmmer.
