### ISSUE TITLE
zipfile.BadZipFile: Bad CRC-32 for file 'alphafold/alphafold_iteration/evoformer/evoformer_iteration/msa_transition/transition2//weights.npy'                                                                                                                             

### ISSUE THREAD

**Issue by avilella** [deepmind/alphafold#394]
We have a copy of the alphafold db including the params/ folder in a hard disk in the computer where we run Alphafold. Every so often (every few weeks), the execution complains about the weights files being corrupted:

```
zipfile.BadZipFile: Bad CRC-32 for file 'alphafold/alphafold_iteration/evoformer/evoformer_iteration/triangle_multiplication_outgoing/right_projection//weights.npy'
```

If we refresh them (`cp -f`) from a copy we keep elsewhere, then everything goes back to normal. Is there a reason why these may be modified? If they are only read by the execution, what could be causing this issue?

Thanks

**Comment by ValZapod** [comment]
Why are they even ckecking crc 32 every run??

**Comment by Augustin-Zidek** [comment]
This looks very weird and nobody has ever reported this before, so I suspect this has to be something unique to your setup/machine. 

It looks like something is corrupting the AlphaFold parameter files. Since AlphaFold just reads these files, I don't suspect AlphaFold is corrupting them. Is it possible the hard drive you are storing them on is faulty or badly formatted?

I recommend checking the health of the drive you are storing the AlphaFold params (and Jackhmmer database) on. Assuming, the drive where the files are is `/dev/sda`, then try running:

```sh
sudo smartctl -a /dev/sda
```

as well as 

```sh
sudo badblocks -v /dev/sda
```

See also https://superuser.com/questions/171195/how-to-check-the-health-of-a-hard-drive for more details.

**Comment by Augustin-Zidek** [comment]
Closing this now, feel free to reopen if this is still an issue.
