### ISSUE TITLE
How to select a predicting model

### ISSUE THREAD

**Issue by jarunan** [deepmind/alphafold#405]
Hi there,

In alphafold/model/config.py, five models are set by default. Is it possible to select only one model out of five for the prediction and via an input argument? I would like to avoid modifying the script config.py.

Thank you

**Comment by Augustin-Zidek** [comment]
Hi, this is currently not possible unfortunately, I recommend modifying the config as a workaround. Note though that due to lower diversity you will most likely get prediction of lower quality.

If you are trying to run only a single model to minimise AlphaFold running time, I suspect reducing the number of models would not help that much since the run time is dominated by the data pipeline, that runs only once for all of the models. 

Also, you could try running with disabled relaxation stage if you want to save some time (but again, you might get predictions with slightly more clashes).
