### ISSUE TITLE
Error #13: Permission denied for 7LIC.cif file

### ISSUE THREAD

**Issue by Shahzebkhan173** [deepmind/alphafold#436]
I am trying to model a multimer (homo-mer) using Alphafold2 but somehow at some part of the code running and terminates at one place with Permission denied Error 
"PermissionError: [Errno 13] Permission denied: '/gpfs/data/gpfs0/our-lab/bin/alphafold/data/db/pdb_mmcif/mmcif_files/7lic.cif'"

Although I have access to these files on our HPC and don't get this error for modeling a single chain.

What could be the problem? any help plz

**Comment by abridgland** [comment]
I would recommend talking to the system administrator for your HPC cluster if you are facing permissions issues, since it is hard to help without having access to your setup. I would also recommend reading this thread which might have some useful information for a similar-sounding issue: https://github.com/deepmind/alphafold/issues/160
