### ISSUE TITLE
About Alphafold DB

### ISSUE THREAD

**Issue by YiningWang2** [deepmind/alphafold#439]

**Comment by nnnwyn** [comment]
Hi, i am quite interested in AlphaDB, i wondering where can i download the plddt score of the whole human proteomes. Thanks a lot.

**Comment by Htomlinson14** [comment]
Hi @YiningWang2 thanks for the question. You will be able to compute this from the AFDB google cloud data. Metadata, including pLDDT fractions, can be queried with bigquery. Otherwise, one could download the data for the whole human proteome using the tax ID 9606 and use the confidence files. Instructions for using the cloud datasets are documented in https://github.com/deepmind/alphafold/tree/main/afdb. Thanks!
