### ISSUE TITLE
OpenMM patch fails in docker build (python version discrepancy)

### ISSUE THREAD

**Issue by mokca** [deepmind/alphafold#46]
When I attempted to build the Docker container for alphafold, the build process failed at step 16/19.  This step involves applying a patch to OpenMM.

I think the issue is that the patch tries to apply to /opt/conda/lib/python3.8 whereas the Docker build image has Python 3.9 installed.  I don't know whether this is caused by a change in miniconda-latest or OS default python versions.

(Ubuntu 18.04 LTS host OS)

**Comment by abridgland** [comment]
Hi, thanks for reporting this. The issue you’re seeing should be fixed in [our commit from yesterday](https://github.com/deepmind/alphafold/commit/0bab1bf84d9d887aba5cfb6d09af1e8c3ecbc408#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddc). Please let us know if you’re still having issues after pulling the latest changes!
