### ISSUE TITLE
ImportError: cannot import name 'types' from 'docker' (/home/user/applications/alphafold/docker/__init__.py)  PYTHONPATH issue

### ISSUE THREAD

**Issue by lizzydizzy42** [deepmind/alphafold#492]
I'm having a similar issue as @davidyanglee , but my ~/.bashrc file(s) don't have the PYTHONPATH variable set to anything. What should it be set to? Or are there other solutions? I've been trying to run everything in a virtual environment and have run "pip3 install -r docker/requirements.txt", apparently successfully, but the 'docker' module doesn't list any functions when I try "dir(docker)" in my virtual environment, as well as in the normal terminal environment.
Thank you.

_Originally posted by @lizzydizzy42 in https://github.com/deepmind/alphafold/issues/474#issuecomment-1144032255_

**Comment by davidyanglee** [comment]
Hi @lizzydizzy42 , I am not an expert on troubleshooting but this is what I found: 1). do the docker build without being in the virtual environment; try adding --no-cache so the build can be more or less from skratch; The pip command within the docker build should not interfere with your system dependency since those pip are built into the docker images (similarly, make sure the directories are not altered in the Dockerfile, unless you really know what the changes mean, since those are for the docker images too); 2). then activate the virtual to do the pip3 installation; maybe even start a fresh new virtual environment. I use python3 -m venv /path_of_venv to create my venv, maybe other ways works fine too but I haven't tried. Again, I am not an expert on these things and just learning on the fly so take this with a grain of salt. Let us know how things go.

**Comment by davidyanglee** [comment]
And you are "source activating" your venv before running alphafold? I usually just created a sh file to activate before, and deactivate after, as it is much easier. If doesn't work, post your entire error message may help other more expert folks troubleshoot with you.
Good luck.
David

**Comment by lizzydizzy42** [comment]
no luck yet. 

Can I check with somebody that the installation uses python3.7? This seems to be my biggest issue. I'm using Ubuntu 20.04, apparently with many python3.8 dependencies. I'm having issues getting my virtual environment to run with python3.7 instead of python3.8.

**Comment by davidyanglee** [comment]
Creating the venv with either Python3.8 or 3.9 worked for me on Ubuntu 20.04 (e.g. "Python3.9 -m venv /path_to_venv/"). But that should have no bearing as far as I know on the docker image build: from the displayed log, docker seems to use Python3.7 for its docker image. A couple of quick check: 1). in your /path_to_venv/bin/ directory, the python version is what you expect; 2). you did run "source /venv_path/bin/activate" to activate the venv before you run the "pip3 install -r docker/requirements.txt" command, while at the alphafold parent dir level; 3). if you type docker images you have successfully created the docker image with the expected creation date/time on there? Also, this may not be directly related to your error but is a new one I noticed and able to fix on my other machine (see thread https://github.com/deepmind/alphafold/issues/478). Easiest fix is just source activate into your venv, then "pip3 install --upgrade protobuf==3.20.0" if you don't want to tinker with the Dockerfile.
