### ISSUE TITLE
Session crashed after using all available RAM (AlphaFold Colab)

### ISSUE THREAD

**Issue by Pankaj-99** [deepmind/alphafold#56]
Hi I'm trying to get oligomeric structure of a protein. I'm able to get the monomer through AlphaFold Colab but when i try to use the oligomeric feature it is crashing. 
Error # Your session crashed after using all available RAM. If you are interested in access to high-RAM runtimes, you may want to check out Colab Pro.

NameError                                 Traceback (most recent call last)
<ipython-input-1-4882f4ef7f6e> in <module>()
      5 use_model = {}
      6 if "model_params" not in dir(): model_params = {}
----> 7 for model_name in ["model_1","model_2","model_3","model_4","model_5"][:num_models]:
      8   use_model[model_name] = True
      9   if model_name not in model_params:
NameError: name 'num_models' is not defined

When i try to use local runtime, getting another error...
Unrecognized runtime "python3"; defaulting to "python2"
Please help, if anyone have any solution for this. 
Thanks
Pankaj

**Comment by abridgland** [comment]
Hi, it seems like notebook that you're using is actually a separate unofficial project rather than our [AlphaFold Colab](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb). Please see their repository here: https://github.com/sokrypton/ColabFold -- hopefully they're able to help with your issue.

We're excited to see how people are using AlphaFold but please note that AlphaFold was not trained or validated on oligomeric structures so we do not support that use case in our Colab at the moment.
