### ISSUE TITLE
How to get pdb structure files in bulk download from Google Cloud

### ISSUE THREAD

**Issue by TrineAalborg** [deepmind/alphafold#590]
Using the described method for whole-proteome structure file download from the Google Cloud database produces the structure files in mmCIF format. Are the structure files available in pdb format for bulk download, and how do I specify this in the download command?

**Comment by Htomlinson14** [comment]
Hi Trine! Thanks for the question. Since PDBx/mmCIF is now the default file format, we don't plan to support pdb formats in general and they aren't available in the cloud dataset. They are, however, available on the EMBL FTP site for SwissProt and various proteomes. There are also open source converters between the two formats that can be found. Thanks!
