### ISSUE TITLE
predicted TM-score (pTM) and predicted aligned errors

### ISSUE THREAD

**Issue by baoxingsong** [deepmind/alphafold#61]
Using the same random seed, looks like 'model_1_ptm' and 'model_1' do not output identical results.
Is there any reason we should use 'model_1_ptm', 'model_2_ptm' ,'model_3_ptm' ,'model_4_ptm' ,'model_5_ptm' V.S. 'model_1', 'model_2' ,'model_3' ,'model_4' ,'model_5'?

Is there any assurance difference, please?

**Comment by abridgland** [comment]
The *_ptm models were fine-tuned from the non-pTM models (see section 1.9.7 in the [supplementary information](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03819-2/MediaObjects/41586_2021_3819_MOESM1_ESM.pdf) of our paper). This is why the outputs from these models do not match exactly.

We recommend running the non-pTM models for structure prediction because these were used in CASP14 and have been the most thoroughly validated. We think that the pTM models are very slightly worse than the regular models (around 0.5 GDT on CASP14). You can also run one of the pTM models separately in order to get predicted aligned error. This is the protocol we use in our Colab notebook (we choose model_2_ptm for predicted aligned errors).

**Comment by MFSeidl** [comment]
Hi @abridgland - I have a question in connection to your last reply. Indeed, I saw on the Colab notebook you run the monomer models and model_2_ptm to obtain the predicted alined error. I thus far used the monomer_ptm to obtain ptm for each model, and I wonder why one would only run a single model? Would you advice to run regular monomer to obtain the 'best' model was these have been validated and then the corresponding (let's say model 1 had the highest average pLDDT) ptm model to obtain the estimates, or would you always use model_2_ptm, and if so, why? Thanks a lot for your answer
