### ISSUE TITLE
Backwards compatibility of AlphaFold 2.3.0 database with prevous versions of the software

### ISSUE THREAD

**Issue by panchyni** [deepmind/alphafold#657]
I am currently working with researchers at my university to update the version and database of AlphaFold on our university's computing cluster. From discussions we had prior to the release of 2.3.0, I had been told that updating the UniProt and PDB databases shouldn't affect the reproducibility of results or functionality of prior versions, given the common file structure and the ability to control the age of models used with input arguments. However, in the 2.3.0 update I noticed that the uniref30 database uses a slightly different folder structure and no longer contains *_db links and *_db.index files. 

As such, I was hoping you could tell me if previous versions of AlphaFold depend on these files or are the *ffdata and *ffindex files sufficient? Ideally, I would like to avoid maintaining multiple databases and/or update scripts running on our system, so it would be ideal if I could simply make a directory in the format of the previous uniprot30 directory and soft link the necessary contents of uniref30 there so that we can maintain a single directory which support all versions of AlphaFold on our cluster. If the *db/db.index file are necessary for prior versions or there is some other conflict I am missing, I would appreciate any additional information you could give me. 

I understand this is more an issue with the community need of our computing cluster than your software, but any information you could provide about the significance or lack their of regarding this change would save me a lot time and possibly errors trying to test it myself. Thank you for you time and consideration.

**Comment by Htomlinson14** [comment]
Hi @panchyni. Yes the *.ffdata and *.ffindex are sufficient to run this step of the msa pipeline. Changing the MSA databases will indeed effect reproducibility of results. In terms of functionality, if you wish to use the code on newer or older versions of the data then in most instances the program will still run, albeit with different results. In the case where the code doesn't work on older data because of breaking changes that have since been introduced, I would recommend using a tagged version of the code from around the same time (or to update the datasets, as this will likely improve performance)

**Comment by panchyni** [comment]
Thanks for the reply @Htomlinson14, this is very useful to know. I am in the process of updating our code and database for 2.3 for exactly the reasons you have described, but its very help that the database should be backwards compatible as this sort of changeover is never clean or quick.
