### ISSUE TITLE
Why the alphafold use only one gpu , even though my system has two gpus.

### ISSUE THREAD

**Issue by jongseo-park** [deepmind/alphafold#66]
Hi,
<br/>
In my workstation, there are two RTX 3080s with the vram of ~ 10 GB (total ~ 20 GB).

However, when I ran the modeling for a long sequence about 1,700 residues, 

the processes named python were allocated to both GPUs,

but the video ram were filled only in the one GPU.

And then, when the all of the video ram in one GPU was filled, 

running was killed with the error message,
'_Cannot create a tensor proto whose content is larger than 2GB_'.

<br/>
How can I use both GPUs simultaneously and equivalently ?

**Comment by abridgland** [comment]
Hi, this code is not designed to make use of more than one GPU so the behaviour you’re seeing is expected. However the error you report is not to do with GPU memory and instead it’s caused by having large inputs. We very rarely see this at the sequence length you mention so it’s likely that your MSA is extremely large. There are a number of ways that you can try to reduce this but one of first things I would suggest is trying to run using the `--preset=reduced_dbs` configuration. Please take a look at issue #43 for more discussion.

**Comment by jongseo-park** [comment]
Thank you for your reply !

**Comment by jongseo-park** [comment]
> Hi, this code is not designed to make use of more than one GPU so the behaviour you’re seeing is expected. However the error you report is not to do with GPU memory and instead it’s caused by having large inputs. We very rarely see this at the sequence length you mention so it’s likely that your MSA is extremely large. There are a number of ways that you can try to reduce this but one of first things I would suggest is trying to run using the `--preset=reduced_dbs` configuration. Please take a look at issue #43 for more discussion.

**Comment by DavidB256** [comment]
What are other ways to reduce MSA?
