### ISSUE TITLE
[Question] Speed up prediction speed on GPUs with large memory?

### ISSUE THREAD

**Issue by ashrafgt** [deepmind/alphafold#74]
## Summary:
I'm looking to learn if what parts of the Alphafold model configuration we can tweak in order to speed up the prediction when sufficiently large GPUs are available.

## Attempts:
We've tried the prediction on relatively large sequences (in the 1200 AA range), and even with our most powerful GPU, we still couldn't get prediction speeds less than 45 mins with one model (excluding the MSA process). To get these best times, we unset the `TF_FORCE_UNIFIED_MEMORY` and `XLA_PYTHON_CLIENT_MEM_FRACTION` variables, but we're hoping there are more possible actions for us to try.

Thank you!

**Comment by abridgland** [comment]
Hi, can you share how you measured the 45 minutes? Was that 45 minutes per model or 45 minutes for all 5 models? And do you know if it included the time to compile the model? You can use `--benchmark` to get separate timings. Also see https://github.com/deepmind/alphafold#inferencing-many-proteins for advice on how to avoid re-compilations when inferencing many proteins if that is relevant to your use case.

In general having more GPU memory won’t help speed up model inference unless you’re finding the GPU memory is full (i.e. you’re overflowing to host RAM). However you may be able to improve speed a bit by using a larger subbatch size (see: https://github.com/deepmind/alphafold/blob/1e216f93f06aa04aa699562f504db1d02c3b704c/alphafold/model/config.py#L325) which trades memory for speed. Picking the right value will depend on your inputs and hardware. Finally, depending on how much you care about accuracy, you could simply run just 1 or 2 models rather than all 5. I hope that helps!

**Comment by ashrafgt** [comment]
Thank you for the reply @abridgland!

I'll try and different the different questions/points here:

> Was that 45 minutes per model or 45 minutes for all 5 models?

We only used one model. Sorry for not including the number of models used during the benchmark in the original post!

> Do you know if it included the time to compile the model?

I'm pretty sure it included the time for compiling the model, as we're running the prediction inside a workflow engine which shows us the overall processing time for the whole prediction routine.

> Also see [link] for advice on how to avoid re-compilations when inferencing many proteins

That isn't currently the target use case, but I'll keep this in mind.

> However you may be able to improve speed a bit by using a larger subbatch size

Awesome! I also suspected that setting could be one of the keys to optimizing the memory usage, but wanted to get an extra opinion as well.

> Depending on how much you care about accuracy, you could simply run just 1 or 2 models rather than all 5

I think we care about the quality of the results than the speed of the process, but we could simply run prediction with multiple models concurrently (potentially all 5), then aggregate the results.


I'll experiment with the `subbatch_size` as you suggested and share the results. Thank you.
