### ISSUE TITLE
AlphaFold/Colab/RunTimeError

### ISSUE THREAD

**Issue by incisrdg** [deepmind/alphafold#755]
I am having trouble about doing protein prediction via AlphaFold colab. I used to predict structures until now, but at the last time I received an RunTimeError on line 409 and 358. Error on line 409 saying that RuntimeError: Error running shell script install_colabfold.sh, output in log file install_log.txt while error on line 358 just saying RunTimeError. The screenshot of errors can be find via the image I uploaded. How can I solve this problem. I've never had this kind of problem before.

<img width="631" alt="Screenshot 2023-04-28 at 10 15 58" src="https://user-images.githubusercontent.com/128684506/235080427-27446ed7-5af1-4f88-9f56-ce89ae29e0bb.png">

**Comment by tomgoddard** [comment]
This error is because Google Colab updated today from Python 3.9 to 3.10 and the old version of ColabFold that ChimeraX is using will not run on Python 3.10 because it requires an old version of pypi package tensorflow-cpu (< 2.8).

 This is a ChimeraX issue and the ChimeraX developer (me) needs to update to a newer ColabFold version.  The ChimeraX bug report is here (see comment 4 for a way to work around the error)

    https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/8911

This alphafold ticket can be closed since the problem is with ChimeraX and ColabFold, not with Alphafold.

**Comment by tomgoddard** [comment]
I have fixed ChimeraX prediction now using a new (March 8) version of ColabFold.

Turning on energy minimization does not work because OpenMM 7.5.1 that ColabFold uses will not install with Python 3.10.  When I am back to work in a few weeks I will try to update that to openmm 8.0.0.

**Comment by Augustin-Zidek** [comment]
This should now be fixed - we upgraded OpenMM to version 7.7.0 which is compatible with Python 3.10. Let me know if you encounter any further issues.
