### ISSUE TITLE
Building wheel for dm-tree (setup.py) ... error

### ISSUE THREAD

**Issue by ZQiangdeng** [deepmind/alphafold#84]
When I use command: "
# python pkgs
pip3 install --upgrade pip \
    && pip3 install -r ./requirements.txt \
    && pip3 install --upgrade "jax[cuda111]" -f \
    https://storage.googleapis.com/jax-releases/jax_releases.html"
and the feedback
![image](https://user-images.githubusercontent.com/62085217/127728597-6609a60f-f7c8-43d9-8447-7d02717e2c1c.png)

**Comment by sci3** [comment]
me too 
but I use conda install dm-tree==0.1.5

**Comment by ZQiangdeng** [comment]
Thanks，conda does work



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 1, 2021 22:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deepmind/alphafold] Building wheel for dm-tree (setup.py) ... error (#84)




 
me too
 but I use conda install dm-tree==0.1.5

**Comment by tomwardio** [comment]
Thank you for reporting. This is likely due to the Linux distribution you're using not having a corresponding PyPi wheel for [dm-tree](https://github.com/deepmind/tree), requiring it to be compiled from source. I'm glad to hear the conda repository works for your setup, if you have any further issues please reach out to the `dm-tree` maintainers.
