### ISSUE TITLE
meet problem in path -p openmm.patch

### ISSUE THREAD

**Issue by sci3** [deepmind/alphafold#86]
Do you have meet problem in 
path -p0 < alphafold/docker/openmm.patch

---Original---
From: ***@***.***&gt;
Date: Sun, Aug 1, 2021 22:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deepmind/alphafold] Building wheel for dm-tree (setup.py) ... error (#84)

 
me too
 but I use conda install dm-tree==0.1.5
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @ZQiangdeng in https://github.com/deepmind/alphafold/issues/84#issuecomment-890530553_

**Comment by ZQiangdeng** [comment]
no&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 1, 2021 23:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: [deepmind/alphafold] I meet problem (#86)




 
Do you have meet problem in
 path -p0 < alphafold/docker/openmm.patch
 
---Original---
 From: @.&gt;
 Date: Sun, Aug 1, 2021 22:05 PM
 To: @.&gt;;
 Cc: @.@.&gt;;
 Subject: Re: [deepmind/alphafold] Building wheel for dm-tree (setup.py) ... error (#84)
 
me too
 but I use conda install dm-tree==0.1.5
 
—
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
Originally posted by @ZQiangdeng in #84 (comment)

**Comment by ZQiangdeng** [comment]
I meet another problem:&nbsp; &nbsp;
aria2c: error while loading shared libraries: libssl.so.1.0.0: can not open shared object file: no such file or directory.&nbsp;
I don't have root permission. Do you have any idea about it?&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 1, 2021 23:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: [deepmind/alphafold] I meet problem (#86)




 
Do you have meet problem in
 path -p0 < alphafold/docker/openmm.patch
 
---Original---
 From: @.&gt;
 Date: Sun, Aug 1, 2021 22:05 PM
 To: @.&gt;;
 Cc: @.@.&gt;;
 Subject: Re: [deepmind/alphafold] Building wheel for dm-tree (setup.py) ... error (#84)
 
me too
 but I use conda install dm-tree==0.1.5
 
—
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
Originally posted by @ZQiangdeng in #84 (comment)

**Comment by sci3** [comment]
I had a problem installing the patch;

####################################################################################
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: simtk/openmm/app/topology.py
|===================================================================
|--- simtk.orig/openmm/app/topology.py
|+++ simtk/openmm/app/topology.py
--------------------------
######################################################################################

my command is
#########################################################################################
cd ~/anaconda3/envs/alphafold/lib/python3.8/site-packages/ && patch -p0 < $alphafold_path/docker/openmm.patch
#########################################################################################

I can't fix it
